cache:
  paths:
    - ./node_modules/

stages:
  - build
  - cleanup
  - deploy

build:
  stage: build
  script:
    - npm install && gulp build --lang fr-FR
  only:
    - master
  tags:
    - deployBuild
  allow_failure: true


cleaning:
  stage: cleanup
  script: rm -rf $PWD
  when: always

deploying:
  stage: deploy
  script: curl --data "rep=$CI_PROJECT_DIR" http://vspar-infodyn-p-db-01.afp.com/
  when: on_success
