build:
  stage: build
  script:
    - npm install && gulp build --lang fr-FR
    - cp -R ./build /home/gitlab-runner/deploy
  only:
    - master
  tags:
    - deployBuild

deploying:
  stage: deploy
  script:
    - curl --data "rep=$CI_PROJECT_DIR" http://vspar-infodyn-p-db-01.afp.com:8666
  when: on_success
  only:
    - master
  tags:
    - deployBuild
