cache:
  paths:
    - ./node_modules/

build:
  stage: build
  script:
    - npm install && gulp build --lang fr-FR
    - cp -R ./build /home/gitlab-runner/deploy/
    - echo $CI_PROJECT_DIR
  only:
    - master
  tags:
    - deployBuild
  allow_failure: true
