cache:
  paths:
    - ./node_modules/

stages:
  - build
  - cleanup

build:
  stage: build
  script:
    - npm install && gulp build --lang fr-FR
    - cp -R ./build /home/gitlab-runner/deploy/
    - export
  only:
    - master
  tags:
    - deployBuild
  allow_failure: true


cleaning:
  stage: cleanup
  script: rm -rf $PWD
  when: always
