variables:
  CI_BUILD_TARGET: ""
build:
  stage: build
  script:
    - npm install && gulp build --lang fr-FR
    - mkdir $HOME/deploy/$CI_BUILD_ID && cp -R ./build/* $HOME/deploy/$CI_BUILD_ID/
    - $CI_BUILD_TARGET = "$CI_BUILD_ID"
  only:
    - master
  tags:
    - deployBuild

deploying:
  stage: deploy
  script:
    - curl --data "toclean=$CI_PROJECT_DIR&build=$HOME/deploy/$CI_BUILD_TARGET" http://vspar-infodyn-p-db-01.afp.com:8666
  when: on_success
  only:
    - master
  tags:
    - deployBuild
