before_script:
  - npm install gulp -g && npm install

deploy:
  script: gulp build --lang fr-FR
  stage: build
  only:
    - master
  tags:
    - deployBuild
  allow_failure: true

on_success:
  - echo success!
