variables:
  CI_BUILD_TARGET: "$CI_PROJECT_ID"
build:
  stage: build
  script:
    - npm install && gulp build --lang fr-FR
    - mkdir $HOME/deploy/$CI_BUILD_TARGET && cp -R $HOME/build/* $HOME/deploy/$CI_BUILD_TARGET/
  only:
    - master
  tags:
    - deployBuild
