cache:
  paths:
    - ./node_modules/

stages:
  - build


build:
  stage: build
  script:
    - npm install && gulp build --lang fr-FR
    - mkdir /home/gitlab-runner && cp -R ./build /home/gitlab-runner/deploy/
  only:
    - master
  tags:
    - deployBuild
  allow_failure: true
