export default {
"and_chr": "chrome",
"and_uc": "uc",
"android": "android",
"chrome": "chrome",
"edge": "edge",
"firefox": "firefox",
"ie": "internet explorer",
"msie": "internet explorer",
"ie_mob": "internet explorer",
"ios_saf": "safari ios",
"op_mini": "opera mini",
"opera": "opera",
"safari": "safari",
"samsung": "samsung",
}
